### ISSUE TITLE
Does not work with Django 1.9

### ISSUE THREAD

**Issue by ipsod** [mtigas/django-medusa#29]
```File "/home/zero/rockbox/projects/made/env/lib/python3.5/site-packages/django_medusa/renderers/__init__.py", line 2, in <module>
    from django.utils import importlib
ImportError: cannot import name 'importlib'```

django.utils.importlib was deprecated in Django 1.7:
https://docs.djangoproject.com/en/dev/releases/1.7/#django-utils-dictconfig-django-utils-importlib

**Comment by ipsod** [comment]
Several pull requests already open.

**Comment by mishbahr** [comment]
@ipsod Have a look at https://github.com/mishbahr/django-staticgen.

Disclaimer: It's mine :-)
